### ISSUE TITLE
Greek Iota is misplaced

### ISSUE THREAD

**Issue by fukanchik** [tonsky/font-writer#2]
See screenshot:
![image](https://user-images.githubusercontent.com/967289/144787915-3bcffd16-f43f-488d-9ced-63185510dd75.png)
(word "καινούρια")
..and here there is just one space but looks like two:
![image](https://user-images.githubusercontent.com/967289/144788057-6cdf07ff-db23-4d8f-8fb2-30edf735afbb.png)
(text "και καλαμάρια")

**Comment by tonsky** [comment]
Thanks, I’ll take a look soon!

**Comment by tonsky** [comment]
So the problem is that IBM Plex Mono doesn’t have Greek at all. Writer is based on IBM Plex Mono, so it doesn’t have it too. What you see is a some other fallback font, not Writer.

I don’t feel that I can do full Greek alphabet on my own, even though I’d like to have it

**Comment by fukanchik** [comment]
Ack. No problem then. 

Is it possible to find out using linux command line what exactly the fallback font is?

**Comment by tonsky** [comment]
No idea, sorry
